baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'gallery'
theme = 'bridget'

# theme as module
[module]
replacements = "github.com/Sped0n/bridget -> themes/bridget"
[[module.imports]]
path = "github.com/Sped0n/bridget"
